/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.dun.open_process_flow.api;

import com.dun.open_process_flow.model.BulkImportPost201Response;
import com.dun.open_process_flow.model.Error;
import com.dun.open_process_flow.model.ProcessFlowExport;
import com.dun.open_process_flow.model.ProcessFlowImport;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-10T17:34:15.048460300+03:00[Africa/Nairobi]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "Bulk Operations", description = "Bulk import and export operations")
public interface BulkApi {

    default BulkApiDelegate getDelegate() {
        return new BulkApiDelegate() {};
    }

    String PATH_BULK_EXPORT_GET = "/bulk/export";
    /**
     * GET /bulk/export : Bulk export process flow
     * Exports the complete process flow in JSON format
     *
     * @return Export successful (status code 200)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "bulkExportGet",
        summary = "Bulk export process flow",
        description = "Exports the complete process flow in JSON format",
        tags = { "Bulk Operations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Export successful", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProcessFlowExport.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = BulkApi.PATH_BULK_EXPORT_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<ProcessFlowExport> bulkExportGet(
        
    ) {
        return getDelegate().bulkExportGet();
    }


    String PATH_BULK_IMPORT_POST = "/bulk/import";
    /**
     * POST /bulk/import : Bulk import process flow
     * Imports a complete process flow from JSON format. This endpoint accepts the same JSON structure as your original file and populates all tables accordingly. 
     *
     * @param processFlowImport  (required)
     * @return Import successful (status code 201)
     *         or Bad request - invalid input (status code 400)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "bulkImportPost",
        summary = "Bulk import process flow",
        description = "Imports a complete process flow from JSON format. This endpoint accepts the same JSON structure as your original file and populates all tables accordingly. ",
        tags = { "Bulk Operations" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Import successful", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BulkImportPost201Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = BulkApi.PATH_BULK_IMPORT_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BulkImportPost201Response> bulkImportPost(
        @Parameter(name = "ProcessFlowImport", description = "", required = true) @Valid @RequestBody ProcessFlowImport processFlowImport
    ) {
        return getDelegate().bulkImportPost(processFlowImport);
    }

}
