/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.dun.open_process_flow.api;

import com.dun.open_process_flow.model.HealthGet200Response;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-10T17:34:15.048460300+03:00[Africa/Nairobi]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "Bulk Operations", description = "Bulk import and export operations")
public interface HealthApi {

    default HealthApiDelegate getDelegate() {
        return new HealthApiDelegate() {};
    }

    String PATH_HEALTH_GET = "/health";
    /**
     * GET /health : Health check
     * Check API health status
     *
     * @return API is healthy (status code 200)
     */
    @Operation(
        operationId = "healthGet",
        summary = "Health check",
        description = "Check API health status",
        tags = { "Bulk Operations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "API is healthy", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = HealthGet200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = HealthApi.PATH_HEALTH_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<HealthGet200Response> healthGet(
        
    ) {
        return getDelegate().healthGet();
    }

}
