/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.dun.open_process_flow.api;

import com.dun.open_process_flow.model.Error;
import com.dun.open_process_flow.model.LaneInput;
import com.dun.open_process_flow.model.LanesGet200Response;
import com.dun.open_process_flow.model.LanesIdDelete200Response;
import com.dun.open_process_flow.model.LanesIdGet200Response;
import com.dun.open_process_flow.model.LanesIdPut200Response;
import com.dun.open_process_flow.model.LanesPost201Response;
import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-10T17:34:15.048460300+03:00[Africa/Nairobi]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "Lanes", description = "Operations related to process lanes")
public interface LanesApi {

    default LanesApiDelegate getDelegate() {
        return new LanesApiDelegate() {};
    }

    String PATH_LANES_GET = "/lanes";
    /**
     * GET /lanes : Get all lanes
     * Retrieves a list of all lanes ordered by position
     *
     * @param sort Field to sort by (optional, default to position)
     * @return Successful response (status code 200)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "lanesGet",
        summary = "Get all lanes",
        description = "Retrieves a list of all lanes ordered by position",
        tags = { "Lanes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LanesGet200Response.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = LanesApi.PATH_LANES_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<LanesGet200Response> lanesGet(
        @Parameter(name = "sort", description = "Field to sort by", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sort", required = false, defaultValue = "position") String sort
    ) {
        return getDelegate().lanesGet(sort);
    }


    String PATH_LANES_ID_DELETE = "/lanes/{id}";
    /**
     * DELETE /lanes/{id} : Delete lane
     * Deletes a lane and all associated nodes (cascade)
     *
     * @param id Lane ID (required)
     * @return Lane deleted successfully (status code 200)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "lanesIdDelete",
        summary = "Delete lane",
        description = "Deletes a lane and all associated nodes (cascade)",
        tags = { "Lanes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lane deleted successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LanesIdDelete200Response.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = LanesApi.PATH_LANES_ID_DELETE,
        produces = { "application/json" }
    )
    default ResponseEntity<LanesIdDelete200Response> lanesIdDelete(
        @NotNull @Parameter(name = "id", description = "Lane ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    ) {
        return getDelegate().lanesIdDelete(id);
    }


    String PATH_LANES_ID_GET = "/lanes/{id}";
    /**
     * GET /lanes/{id} : Get lane by ID
     * Retrieves a specific lane by its ID
     *
     * @param id Lane ID (required)
     * @return Successful response (status code 200)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "lanesIdGet",
        summary = "Get lane by ID",
        description = "Retrieves a specific lane by its ID",
        tags = { "Lanes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LanesIdGet200Response.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = LanesApi.PATH_LANES_ID_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<LanesIdGet200Response> lanesIdGet(
        @NotNull @Parameter(name = "id", description = "Lane ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    ) {
        return getDelegate().lanesIdGet(id);
    }


    String PATH_LANES_ID_PUT = "/lanes/{id}";
    /**
     * PUT /lanes/{id} : Update lane
     * Updates an existing lane
     *
     * @param id Lane ID (required)
     * @param laneInput  (required)
     * @return Lane updated successfully (status code 200)
     *         or Bad request - invalid input (status code 400)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "lanesIdPut",
        summary = "Update lane",
        description = "Updates an existing lane",
        tags = { "Lanes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lane updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LanesIdPut200Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = LanesApi.PATH_LANES_ID_PUT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<LanesIdPut200Response> lanesIdPut(
        @NotNull @Parameter(name = "id", description = "Lane ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "LaneInput", description = "", required = true) @Valid @RequestBody LaneInput laneInput
    ) {
        return getDelegate().lanesIdPut(id, laneInput);
    }


    String PATH_LANES_POST = "/lanes";
    /**
     * POST /lanes : Create a new lane
     * Creates a new process lane
     *
     * @param laneInput  (required)
     * @return Lane created successfully (status code 201)
     *         or Bad request - invalid input (status code 400)
     *         or Conflict - resource already exists (status code 409)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "lanesPost",
        summary = "Create a new lane",
        description = "Creates a new process lane",
        tags = { "Lanes" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Lane created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LanesPost201Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict - resource already exists", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = LanesApi.PATH_LANES_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<LanesPost201Response> lanesPost(
        @Parameter(name = "LaneInput", description = "", required = true) @Valid @RequestBody LaneInput laneInput
    ) {
        return getDelegate().lanesPost(laneInput);
    }

}
