/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.dun.open_process_flow.api;

import com.dun.open_process_flow.model.Error;
import com.dun.open_process_flow.model.NodeInput;
import com.dun.open_process_flow.model.NodesGet200Response;
import com.dun.open_process_flow.model.NodesIdChildrenChildIdDelete200Response;
import com.dun.open_process_flow.model.NodesIdChildrenGet200Response;
import com.dun.open_process_flow.model.NodesIdChildrenPost201Response;
import com.dun.open_process_flow.model.NodesIdChildrenPostRequest;
import com.dun.open_process_flow.model.NodesIdDelete200Response;
import com.dun.open_process_flow.model.NodesIdGet200Response;
import com.dun.open_process_flow.model.NodesIdPatchRequest;
import com.dun.open_process_flow.model.NodesIdPut200Response;
import com.dun.open_process_flow.model.NodesIdTextsGet200Response;
import com.dun.open_process_flow.model.NodesIdTextsPost201Response;
import com.dun.open_process_flow.model.NodesIdTextsPostRequest;
import com.dun.open_process_flow.model.NodesIdTextsPut200Response;
import com.dun.open_process_flow.model.NodesIdTextsPutRequest;
import com.dun.open_process_flow.model.NodesIdTextsTextIdDelete200Response;
import com.dun.open_process_flow.model.NodesIdTextsTextIdPut200Response;
import com.dun.open_process_flow.model.NodesIdTextsTextIdPutRequest;
import com.dun.open_process_flow.model.NodesPost201Response;
import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-10T17:34:15.048460300+03:00[Africa/Nairobi]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "Nodes", description = "Operations related to process nodes")
public interface NodesApi {

    default NodesApiDelegate getDelegate() {
        return new NodesApiDelegate() {};
    }

    String PATH_NODES_GET = "/nodes";
    /**
     * GET /nodes : Get all nodes
     * Retrieves all nodes with optional filtering
     *
     * @param laneId Filter by lane ID (optional)
     * @param state Filter by state (optional)
     * @param focused Filter by focused status (optional)
     * @param includeTexts Include node texts in response (optional, default to false)
     * @param includeChildren Include children relationships (optional, default to false)
     * @return Successful response (status code 200)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "nodesGet",
        summary = "Get all nodes",
        description = "Retrieves all nodes with optional filtering",
        tags = { "Nodes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NodesGet200Response.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = NodesApi.PATH_NODES_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<NodesGet200Response> nodesGet(
        @Parameter(name = "lane_id", description = "Filter by lane ID", in = ParameterIn.QUERY) @Valid @RequestParam(value = "lane_id", required = false) @Nullable String laneId,
        @Parameter(name = "state", description = "Filter by state", in = ParameterIn.QUERY) @Valid @RequestParam(value = "state", required = false) @Nullable String state,
        @Parameter(name = "focused", description = "Filter by focused status", in = ParameterIn.QUERY) @Valid @RequestParam(value = "focused", required = false) @Nullable Boolean focused,
        @Parameter(name = "include_texts", description = "Include node texts in response", in = ParameterIn.QUERY) @Valid @RequestParam(value = "include_texts", required = false, defaultValue = "false") Boolean includeTexts,
        @Parameter(name = "include_children", description = "Include children relationships", in = ParameterIn.QUERY) @Valid @RequestParam(value = "include_children", required = false, defaultValue = "false") Boolean includeChildren
    ) {
        return getDelegate().nodesGet(laneId, state, focused, includeTexts, includeChildren);
    }


    String PATH_NODES_ID_CHILDREN_CHILD_ID_DELETE = "/nodes/{id}/children/{child_id}";
    /**
     * DELETE /nodes/{id}/children/{child_id} : Remove child from node
     * Removes a parent-child relationship
     *
     * @param id Node ID (required)
     * @param childId Child node ID (required)
     * @return Child relationship removed successfully (status code 200)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "nodesIdChildrenChildIdDelete",
        summary = "Remove child from node",
        description = "Removes a parent-child relationship",
        tags = { "Node Children" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Child relationship removed successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NodesIdChildrenChildIdDelete200Response.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = NodesApi.PATH_NODES_ID_CHILDREN_CHILD_ID_DELETE,
        produces = { "application/json" }
    )
    default ResponseEntity<NodesIdChildrenChildIdDelete200Response> nodesIdChildrenChildIdDelete(
        @NotNull @Parameter(name = "id", description = "Node ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @NotNull @Parameter(name = "child_id", description = "Child node ID", required = true, in = ParameterIn.PATH) @PathVariable("child_id") String childId
    ) {
        return getDelegate().nodesIdChildrenChildIdDelete(id, childId);
    }


    String PATH_NODES_ID_CHILDREN_GET = "/nodes/{id}/children";
    /**
     * GET /nodes/{id}/children : Get node children
     * Retrieves all children of a specific node
     *
     * @param id Node ID (required)
     * @return Successful response (status code 200)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "nodesIdChildrenGet",
        summary = "Get node children",
        description = "Retrieves all children of a specific node",
        tags = { "Node Children" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NodesIdChildrenGet200Response.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = NodesApi.PATH_NODES_ID_CHILDREN_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<NodesIdChildrenGet200Response> nodesIdChildrenGet(
        @NotNull @Parameter(name = "id", description = "Node ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    ) {
        return getDelegate().nodesIdChildrenGet(id);
    }


    String PATH_NODES_ID_CHILDREN_POST = "/nodes/{id}/children";
    /**
     * POST /nodes/{id}/children : Add child to node
     * Creates a parent-child relationship between nodes
     *
     * @param id Node ID (required)
     * @param nodesIdChildrenPostRequest  (required)
     * @return Child relationship created successfully (status code 201)
     *         or Bad request - invalid input (status code 400)
     *         or Resource not found (status code 404)
     *         or Conflict - resource already exists (status code 409)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "nodesIdChildrenPost",
        summary = "Add child to node",
        description = "Creates a parent-child relationship between nodes",
        tags = { "Node Children" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Child relationship created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NodesIdChildrenPost201Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict - resource already exists", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = NodesApi.PATH_NODES_ID_CHILDREN_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<NodesIdChildrenPost201Response> nodesIdChildrenPost(
        @NotNull @Parameter(name = "id", description = "Node ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "NodesIdChildrenPostRequest", description = "", required = true) @Valid @RequestBody NodesIdChildrenPostRequest nodesIdChildrenPostRequest
    ) {
        return getDelegate().nodesIdChildrenPost(id, nodesIdChildrenPostRequest);
    }


    String PATH_NODES_ID_COMPLETE_GET = "/nodes/{id}/complete";
    /**
     * GET /nodes/{id}/complete : Get complete node data
     * Retrieves a node with all related data (lane, texts, children)
     *
     * @param id Node ID (required)
     * @return Successful response (status code 200)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "nodesIdCompleteGet",
        summary = "Get complete node data",
        description = "Retrieves a node with all related data (lane, texts, children)",
        tags = { "Nodes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NodesIdGet200Response.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = NodesApi.PATH_NODES_ID_COMPLETE_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<NodesIdGet200Response> nodesIdCompleteGet(
        @NotNull @Parameter(name = "id", description = "Node ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    ) {
        return getDelegate().nodesIdCompleteGet(id);
    }


    String PATH_NODES_ID_DELETE = "/nodes/{id}";
    /**
     * DELETE /nodes/{id} : Delete node
     * Deletes a node and all associated data
     *
     * @param id Node ID (required)
     * @return Node deleted successfully (status code 200)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "nodesIdDelete",
        summary = "Delete node",
        description = "Deletes a node and all associated data",
        tags = { "Nodes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Node deleted successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NodesIdDelete200Response.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = NodesApi.PATH_NODES_ID_DELETE,
        produces = { "application/json" }
    )
    default ResponseEntity<NodesIdDelete200Response> nodesIdDelete(
        @NotNull @Parameter(name = "id", description = "Node ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    ) {
        return getDelegate().nodesIdDelete(id);
    }


    String PATH_NODES_ID_GET = "/nodes/{id}";
    /**
     * GET /nodes/{id} : Get node by ID
     * Retrieves a specific node with optional related data
     *
     * @param id Node ID (required)
     * @param includeTexts Include node texts (optional, default to true)
     * @param includeChildren Include children relationships (optional, default to true)
     * @return Successful response (status code 200)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "nodesIdGet",
        summary = "Get node by ID",
        description = "Retrieves a specific node with optional related data",
        tags = { "Nodes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NodesIdGet200Response.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = NodesApi.PATH_NODES_ID_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<NodesIdGet200Response> nodesIdGet(
        @NotNull @Parameter(name = "id", description = "Node ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "include_texts", description = "Include node texts", in = ParameterIn.QUERY) @Valid @RequestParam(value = "include_texts", required = false, defaultValue = "true") Boolean includeTexts,
        @Parameter(name = "include_children", description = "Include children relationships", in = ParameterIn.QUERY) @Valid @RequestParam(value = "include_children", required = false, defaultValue = "true") Boolean includeChildren
    ) {
        return getDelegate().nodesIdGet(id, includeTexts, includeChildren);
    }


    String PATH_NODES_ID_PATCH = "/nodes/{id}";
    /**
     * PATCH /nodes/{id} : Partially update node
     * Updates specific fields of a node
     *
     * @param id Node ID (required)
     * @param nodesIdPatchRequest  (required)
     * @return Node updated successfully (status code 200)
     *         or Bad request - invalid input (status code 400)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "nodesIdPatch",
        summary = "Partially update node",
        description = "Updates specific fields of a node",
        tags = { "Nodes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Node updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NodesIdPut200Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = NodesApi.PATH_NODES_ID_PATCH,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<NodesIdPut200Response> nodesIdPatch(
        @NotNull @Parameter(name = "id", description = "Node ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "NodesIdPatchRequest", description = "", required = true) @Valid @RequestBody NodesIdPatchRequest nodesIdPatchRequest
    ) {
        return getDelegate().nodesIdPatch(id, nodesIdPatchRequest);
    }


    String PATH_NODES_ID_PUT = "/nodes/{id}";
    /**
     * PUT /nodes/{id} : Update node
     * Updates an existing node
     *
     * @param id Node ID (required)
     * @param nodeInput  (required)
     * @return Node updated successfully (status code 200)
     *         or Bad request - invalid input (status code 400)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "nodesIdPut",
        summary = "Update node",
        description = "Updates an existing node",
        tags = { "Nodes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Node updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NodesIdPut200Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = NodesApi.PATH_NODES_ID_PUT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<NodesIdPut200Response> nodesIdPut(
        @NotNull @Parameter(name = "id", description = "Node ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "NodeInput", description = "", required = true) @Valid @RequestBody NodeInput nodeInput
    ) {
        return getDelegate().nodesIdPut(id, nodeInput);
    }


    String PATH_NODES_ID_TEXTS_GET = "/nodes/{id}/texts";
    /**
     * GET /nodes/{id}/texts : Get node texts
     * Retrieves all text descriptions for a node
     *
     * @param id Node ID (required)
     * @return Successful response (status code 200)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "nodesIdTextsGet",
        summary = "Get node texts",
        description = "Retrieves all text descriptions for a node",
        tags = { "Node Texts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NodesIdTextsGet200Response.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = NodesApi.PATH_NODES_ID_TEXTS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<NodesIdTextsGet200Response> nodesIdTextsGet(
        @NotNull @Parameter(name = "id", description = "Node ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    ) {
        return getDelegate().nodesIdTextsGet(id);
    }


    String PATH_NODES_ID_TEXTS_POST = "/nodes/{id}/texts";
    /**
     * POST /nodes/{id}/texts : Add text to node
     * Adds a new text description to a node
     *
     * @param id Node ID (required)
     * @param nodesIdTextsPostRequest  (required)
     * @return Text added successfully (status code 201)
     *         or Bad request - invalid input (status code 400)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "nodesIdTextsPost",
        summary = "Add text to node",
        description = "Adds a new text description to a node",
        tags = { "Node Texts" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Text added successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NodesIdTextsPost201Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = NodesApi.PATH_NODES_ID_TEXTS_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<NodesIdTextsPost201Response> nodesIdTextsPost(
        @NotNull @Parameter(name = "id", description = "Node ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "NodesIdTextsPostRequest", description = "", required = true) @Valid @RequestBody NodesIdTextsPostRequest nodesIdTextsPostRequest
    ) {
        return getDelegate().nodesIdTextsPost(id, nodesIdTextsPostRequest);
    }


    String PATH_NODES_ID_TEXTS_PUT = "/nodes/{id}/texts";
    /**
     * PUT /nodes/{id}/texts : Replace all node texts
     * Replaces all existing texts for a node with new ones
     *
     * @param id Node ID (required)
     * @param nodesIdTextsPutRequest  (required)
     * @return Texts replaced successfully (status code 200)
     *         or Bad request - invalid input (status code 400)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "nodesIdTextsPut",
        summary = "Replace all node texts",
        description = "Replaces all existing texts for a node with new ones",
        tags = { "Node Texts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Texts replaced successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NodesIdTextsPut200Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = NodesApi.PATH_NODES_ID_TEXTS_PUT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<NodesIdTextsPut200Response> nodesIdTextsPut(
        @NotNull @Parameter(name = "id", description = "Node ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "NodesIdTextsPutRequest", description = "", required = true) @Valid @RequestBody NodesIdTextsPutRequest nodesIdTextsPutRequest
    ) {
        return getDelegate().nodesIdTextsPut(id, nodesIdTextsPutRequest);
    }


    String PATH_NODES_ID_TEXTS_TEXT_ID_DELETE = "/nodes/{id}/texts/{text_id}";
    /**
     * DELETE /nodes/{id}/texts/{text_id} : Delete text
     * Deletes a specific text entry
     *
     * @param id Node ID (required)
     * @param textId Text ID (required)
     * @return Text deleted successfully (status code 200)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "nodesIdTextsTextIdDelete",
        summary = "Delete text",
        description = "Deletes a specific text entry",
        tags = { "Node Texts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Text deleted successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NodesIdTextsTextIdDelete200Response.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = NodesApi.PATH_NODES_ID_TEXTS_TEXT_ID_DELETE,
        produces = { "application/json" }
    )
    default ResponseEntity<NodesIdTextsTextIdDelete200Response> nodesIdTextsTextIdDelete(
        @NotNull @Parameter(name = "id", description = "Node ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @NotNull @Parameter(name = "text_id", description = "Text ID", required = true, in = ParameterIn.PATH) @PathVariable("text_id") Integer textId
    ) {
        return getDelegate().nodesIdTextsTextIdDelete(id, textId);
    }


    String PATH_NODES_ID_TEXTS_TEXT_ID_PUT = "/nodes/{id}/texts/{text_id}";
    /**
     * PUT /nodes/{id}/texts/{text_id} : Update text
     * Updates a specific text entry
     *
     * @param id Node ID (required)
     * @param textId Text ID (required)
     * @param nodesIdTextsTextIdPutRequest  (required)
     * @return Text updated successfully (status code 200)
     *         or Bad request - invalid input (status code 400)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "nodesIdTextsTextIdPut",
        summary = "Update text",
        description = "Updates a specific text entry",
        tags = { "Node Texts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Text updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NodesIdTextsTextIdPut200Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = NodesApi.PATH_NODES_ID_TEXTS_TEXT_ID_PUT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<NodesIdTextsTextIdPut200Response> nodesIdTextsTextIdPut(
        @NotNull @Parameter(name = "id", description = "Node ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @NotNull @Parameter(name = "text_id", description = "Text ID", required = true, in = ParameterIn.PATH) @PathVariable("text_id") Integer textId,
        @Parameter(name = "NodesIdTextsTextIdPutRequest", description = "", required = true) @Valid @RequestBody NodesIdTextsTextIdPutRequest nodesIdTextsTextIdPutRequest
    ) {
        return getDelegate().nodesIdTextsTextIdPut(id, textId, nodesIdTextsTextIdPutRequest);
    }


    String PATH_NODES_POST = "/nodes";
    /**
     * POST /nodes : Create a new node
     * Creates a new process node
     *
     * @param nodeInput  (required)
     * @return Node created successfully (status code 201)
     *         or Bad request - invalid input (status code 400)
     *         or Conflict - resource already exists (status code 409)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "nodesPost",
        summary = "Create a new node",
        description = "Creates a new process node",
        tags = { "Nodes" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Node created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NodesPost201Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict - resource already exists", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = NodesApi.PATH_NODES_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<NodesPost201Response> nodesPost(
        @Parameter(name = "NodeInput", description = "", required = true) @Valid @RequestBody NodeInput nodeInput
    ) {
        return getDelegate().nodesPost(nodeInput);
    }

}
